modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT License"

[[mods]]
    modId = "concord"
    version = "${file.jarVersion}"
    displayName = "Concord"
    authors = "sciwhiz12"
    logoFile = "logo.png"
    logoBlur = false
    description = '''
    A Discord chat integration mod.

    Thank you to the following projects, which are repackaged in this mod:
    - JDA, a Java wrapper for the Discord REST API
      - nv-websocket-client, a high-quality WebSocket client implementation in Java
      - OkHttp, a meticulous HTTP client for the JVM, Android, and GraalVM
        - Okio, a modern I/O library for Android, Java, and Kotlin
      - Apache Commons Collections, contains types that extend and augment the Java Collections Framework
      - Jackson, a suite of data-processing tools for Java and the JVM platform, including a streaming JSON parser / generator library
      - Trove, provides high speed Object and primitive collections for Java
      - FindBugs JSR305, the JSR305 Annotations provided by Findbugs
    '''

[[mixins]]
    config = "mixins.concord.json" 

[[dependencies.concord]]
    modId = "neoforge"
    type = "required"
    versionRange = "[20.4.182,20.5.0)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.concord]]
    modId = "minecraft"
    type = "required"
    versionRange = "[1.20.4,1.20.5)"
    ordering = "NONE"
    side = "BOTH"
